/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.syllab.composite.app;

import com.syllab.composite.moda.ModuleA;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(ModuleA.getVersion());
    }
}
